export const categories = [
  {
    text: 'Донат робуксов (моментально)',
    count: 417,
    link: '/roblox/packages',
  },
  { text: 'Подарочные карты', count: 168, link: '/roblox/gift-cards' },
  { text: 'Робуксы (трансфер)', count: 12, link: '/roblox/robux' },
  { text: 'Геймпассы (гифт)', count: 15, link: '/roblox/gamepasses' },
  { text: 'Plus', count: 24, link: '/roblox/plus' },
  { text: 'Аккаунты', count: 112, link: '/roblox/accounts' },
  { text: 'Робуксы (группой)', count: 1, link: '/roblox/group-robux' },
  { text: 'Робуксы (подарком)', count: 3, link: '/roblox/plus-robux' },
  { text: 'Скины', count: 23, link: '/roblox/skins' },
  { text: 'Лимитки', count: 0, link: '/roblox/limiteds' },
  { text: 'Prime Gaming', count: 9, link: '/roblox/prime-gaming' },
  { text: 'Roblox Studio', count: 135, link: '/roblox/studio' },
  { text: 'Услуги', count: 93, link: '/roblox/services' },
  { text: 'Прочее', count: 149, link: '/roblox/other' },
  {
    text: '99 Nights in the Forest',
    count: 286,
    link: '/roblox/99-nights-in-the-forest',
  },
  { text: 'Adopt Me', count: 319, link: '/roblox/adopt-me' },
  { text: 'Anime Adventures', count: 31, link: '/roblox/anime-adventures' },
  { text: 'Anime Crusaders', count: 75, link: '/roblox/anime-crusaders' },
  { text: 'Anime Eternal', count: 142, link: '/roblox/anime-eternal' },
  { text: 'Anime Last Stand', count: 70, link: '/roblox/anime-last-stand' },
  { text: 'Anime Squadron', count: 23, link: '/roblox/anime-squadron' },
  { text: 'Anime Vanguards', count: 232, link: '/roblox/anime-vanguards' },
  { text: 'Arise Crossover', count: 48, link: '/roblox/arise-crossover' },
  { text: 'ASTD X', count: 64, link: '/roblox/all-star-tower-defense' },
  {
    text: 'Attack on Titan Revolution',
    count: 34,
    link: '/roblox/attack-on-titan-revolution',
  },
  { text: 'AUT', count: 178, link: '/roblox/aut' },
  { text: 'Basketball Zero', count: 94, link: '/roblox/basketball-zero' },
  {
    text: 'Bee Swarm Simulator',
    count: 96,
    link: '/roblox/bee-swarm-simulator',
  },
  { text: 'Bite By Night', count: 85, link: '/roblox/bite-by-night' },
  { text: 'Bizarre Lineage', count: 111, link: '/roblox/bizarre-lineage' },
  { text: 'Blade Ball', count: 113, link: '/roblox/blade-ball' },
  { text: 'Blox Fruits', count: 1007, link: '/roblox/blox-fruits' },
  { text: 'Blue Lock Rivals', count: 151, link: '/roblox/blue-lock-rivals' },
  { text: 'Brookhaven RP', count: 107, link: '/roblox/brookhaven-rp' },
  {
    text: 'Bubble Gum Simulator Infinity',
    count: 82,
    link: '/roblox/bubble-gum-simulator-infinity',
  },
  {
    text: 'Creatures of Sonaria',
    count: 159,
    link: '/roblox/creatures-of-sonaria',
  },
  { text: 'Criminality', count: 88, link: '/roblox/criminality' },
  { text: 'Da Hood', count: 58, link: '/roblox/da-hood' },
  { text: 'Dead Rails', count: 72, link: '/roblox/dead-rails' },
  { text: 'Death Ball', count: 43, link: '/roblox/death-ball' },
  {
    text: 'Escape Tsunami For Brainrots',
    count: 154,
    link: '/roblox/escape-tsunami-for-brainrots',
  },
  { text: 'Fisch', count: 380, link: '/roblox/fisch' },
  { text: 'Fish It', count: 133, link: '/roblox/fish-it' },
  { text: 'Forsaken', count: 222, link: '/roblox/forsaken' },
  { text: 'Garden Horizons', count: 58, link: '/roblox/garden-horizons' },
  {
    text: 'Garden Tower Defense',
    count: 131,
    link: '/roblox/garden-tower-defense',
  },
  { text: 'GPO', count: 158, link: '/roblox/grand-piece-online' },
  { text: 'Grow a Garden', count: 566, link: '/roblox/grow-a-garden' },
  { text: 'Grow a Garden 2', count: 799, link: '/roblox/grow-a-garden-2' },
  { text: 'Ink Game', count: 256, link: '/roblox/ink-game' },
  { text: 'Jailbreak', count: 76, link: '/roblox/jailbreak' },
  { text: 'Jujutsu Infinite', count: 113, link: '/roblox/jujutsu-infinite' },
  {
    text: 'Jujutsu Shenanigans',
    count: 135,
    link: '/roblox/jujutsu-shenanigans',
  },
  { text: 'Kick a Lucky Block', count: 85, link: '/roblox/kick-a-lucky-block' },
  { text: 'King Legacy', count: 71, link: '/roblox/king-legacy' },
  { text: 'MM2', count: 779, link: '/roblox/mm2' },
  { text: 'NFT Battle', count: 40, link: '/roblox/nft-battle' },
  { text: 'Pet Simulator 99', count: 82, link: '/roblox/pet-simulator-99' },
  {
    text: 'Plants Vs Brainrots',
    count: 165,
    link: '/roblox/plants-vs-brainrots',
  },
  { text: 'Racket Rivals', count: 42, link: '/roblox/racket-rivals' },
  { text: 'Rivals', count: 483, link: '/roblox/rivals' },
  { text: 'Sailor Piece', count: 552, link: '/roblox/sailor-piece' },
  { text: 'Sol’s RNG', count: 102, link: '/roblox/sols-rng' },
  {
    text: 'Spongebob Tower Defense',
    count: 201,
    link: '/roblox/spongebob-tower-defense',
  },
  { text: 'Steal a Brainrot', count: 1174, link: '/roblox/steal-a-brainrot' },
  { text: 'The Forge', count: 149, link: '/roblox/the-forge' },
  {
    text: 'The Strongest Battlegrounds',
    count: 289,
    link: '/roblox/the-strongest-battlegrounds',
  },
  {
    text: 'Toilet Tower Defense',
    count: 106,
    link: '/roblox/toilet-tower-defense',
  },
  {
    text: 'Tower Defense Simulator',
    count: 257,
    link: '/roblox/tower-defense-simulator',
  },
  { text: 'Type Soul', count: 15, link: '/roblox/type-soul' },
  { text: 'Universal Tower Defense X', count: 105, link: '/roblox/utd' },
  {
    text: 'Untitled Boxing Game',
    count: 19,
    link: '/roblox/untitled-boxing-game',
  },
  {
    text: 'Volleyball Legends',
    count: 220,
    link: '/roblox/volleyball-legends',
  },
  { text: 'VV: ULTIMATUM', count: 26, link: '/roblox/vv-ultimatum' },
  { text: 'War Tycoon', count: 187, link: '/roblox/war-tycoon' },
  { text: 'YBA', count: 65, link: '/roblox/your-bizzare-adventure' },
  { text: 'Прочие игры', count: 741, link: '/roblox/other-games' },
];
